# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: react-native-dialog-view Package

on:
  push:
    tags: 
      - v*

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: echo git ref
        run: |
          echo ¥{{github.ref}}
      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Exit if not on beta branch
        if: endsWith(github.ref, 'beta') == false
        run: exit -1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: beta
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
