name: npm publish

on:
  create:
    tags:
      - v*

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      
      - name: is main branch
        run: echo ${{contains(github.ref, 'beta') == false && contains(steps.extract_version.outputs.version, 'beta') == false}}
        
      - name: publish package
        if: ${{contains(github.ref, 'beta') == false && contains(steps.extract_version.outputs.version, 'beta') == false}}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest

  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: is beta branch
        run: echo ${{contains(github.ref, 'beta') == true && contains(steps.extract_version.outputs.version, 'beta') == true}}
        
      - name: publish package
        if: ${{contains(github.ref, 'beta') == true && contains(steps.extract_version.outputs.version, 'beta') == true}}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: beta
