name: npm publish latest

on:
  create:
    tags:
      - v*

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: is main branch
        run: echo ${{github.ref}} ${{steps.extract_version.outputs.version}} ${{steps.extract_branch.outputs.branch}}
        
      - name: is main branch
        run: echo ${{contains(github.ref, 'main') && contains(steps.extract_version.outputs.version, 'main')}}
        
      - name: publish package
        if: ${{contains(github.ref, 'main') && contains(steps.extract_version.outputs.version, 'main')}}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
